apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-api-config
  namespace: online-shop
data:
  FRAUD_API: http://fraud-api.online-shop.svc.cluster.local:8080
  NOTIFICATION_API: http://notification-api.online-shop.svc.cluster.local:8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api
  namespace: online-shop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-api
  template:
    metadata:
      labels:
        app: payment-api
    spec:
      containers:
        - name: payment-api
          image: 192.168.0.8:30082/cilium-shop/payment-api:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: payment-api-config
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: payment-api
  namespace: online-shop
spec:
  selector:
    app: payment-api
  ports:
    - name: http
      port: 8080
      targetPort: http
