apiVersion: v1
kind: Service
metadata:
  name: redis-online-shop-service
  namespace: online-shop-bd
spec:
  selector:
    app: online-shop-redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: online-shop-bd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: online-shop-redis
  template:
    metadata:
      labels:
        app: online-shop-redis
    spec:
      containers:
        - name: redis
          image: redis:7.4-alpine
          ports:
            - name: redis
              containerPort: 6379
          args:
            - redis-server
          readinessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi

